name: LocalStack Keycloak Extension Tests

on:
  push:
    paths:
      - keycloak/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/keycloak.yml
      - keycloak/**
  workflow_dispatch:

env:
  LOCALSTACK_DISABLE_EVENTS: "1"
  LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup LocalStack and extension
        run: |
          cd keycloak

          docker pull localstack/localstack-pro &
          docker pull quay.io/keycloak/keycloak:26.0 &
          pip install localstack

          make install
          make lint
          make dist
          localstack extensions -v install file://$(ls ./dist/localstack_extension_keycloak-*.tar.gz)

          DEBUG=1 localstack start -d
          localstack wait

      - name: Run integration tests
        run: |
          cd keycloak
          make test

      - name: Print logs
        if: always()
        run: |
          localstack logs
          localstack stop
