name: LocalStack Extensions Utils Tests

on:
  push:
    paths:
      - utils/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/utils.yml
      - utils/**
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd utils
          pip install -e .[dev,test]

      - name: Lint
        run: |
          cd utils
          make lint

      - name: Run unit tests
        run: |
          cd utils
          make test-unit

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd utils
          pip install -e .[dev,test]

      - name: Run integration tests
        run: |
          docker pull moul/grpcbin &
          cd utils
          make test-integration
